learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path

from . import views

#The variable app_name helps Django distinguish this urls.py file from files 
# of the same name in other apps within the project
app_name = 'learning_logs'

urlpatterns = [
    #home page
    path('', views.index, name='index'),
    #Path that shows all topics.
    path('topics/', views.topics, name="topics"),
    path('topics/<int:topic_id>/', views.topic, name="topic"),
    path('new_topic/', views.new_topic, name="new_topic"),
    path('new_entry/<int:topic_id>/', views.new_entry, name="new_entry"),
    path("edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry"),


]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),

]

learning_logs/models.py
from django.db import models
# https://docs.djangoproject.com/en/4.1/ref/models/fields.
# https://docs.djangoproject.com/en/4.1/topics/db/queries

class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model"""
        return self.text
    
class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural ='entries'

    def __str__(self):
        """Return a simple string representing the entry."""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"
        

    

# Create your models here.

learning_logs/forms.py
from django import forms 
from .models import Topic , Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic 
        fields = ["text"]
        labels = {"text": ""}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text":""}
        widgets = {"text": forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from .models import Topic, Entry
from .forms import TopicForm ,EntryForm

# filter() will always give you a QuerySet, even if only a single object matches the query - in this case, it will be a QuerySet containing a single element.
# If you know there is only one object that matches your query, you can use the get() method on a Manager which returns the object directly:
# >>> one_entry = Entry.objects.get(pk=1)

# Create your views here.

def index(request):
    """The home page for Learning log."""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by("date_added")
    context = {"Topics": topics}
    #print("Topics=",topics)
    return render(request, "learning_logs/topics.html", context)


def topic(request, topic_id):
    """Show a single topoic and all its entries."""
    topic= Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {"topic": topic, "entries": entries}
    return render(request, 'learning_logs/topic.html', context)


def new_topic(request):
    """Add a new topic."""
    if request.method != "POST":
        #No data submitted; create a blank form.
        form = TopicForm()
    else:
        #Post data submitted; process data.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
        
    #display a blank or invalid form.
    context =  {"form": form}
    return render(request, "learning_logs/new_topic.html", context)

def new_entry(request,topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    
    if request.method != "POST":
        #No data submited; create a blank form.
        form = EntryForm()
    else:
        #POST data submitted; process data.
        
        form = EntryForm(data=request.POST)
        
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect("learning_logs:topic", topic_id=topic_id)
        
     # Display a blank or invalid form.

    context = {'topic': topic, 'form': form}
    return render(request, "learning_logs/new_entry.html", context)

def edit_entry(request,entry_id):
    """Edit a existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != "POST":
        # Initial request; pre_fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # POST date submitted; process data.
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("learning_logs:topic", topic_id=topic.id)
    
    context = { "entry": entry, "topic": topic, "form": form }
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>
{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Edit entry:</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <button name="submit">Save changes</button>
    </form>    
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{%extends "learning_logs/base.html" %}

{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic you're interested in.</p>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}

    <p><a href="{% url "learning_logs:topic" topic.id %}">{{ topic }}</a> </p>
    <p>Add a new entry:</p>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token%}
        {{ form.as_div }}

        <button name='submit'> Add entry</button>
    </form>
    
{% endblock content  %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Add a new topic:</p>

<form action="{%url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Add topic</button>
<form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Topic: {{ topic.text }}</p>

<p>Entries:</p>
<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry<a>
</p>

<ul>
    {% for entry in entries%}
    <li>
        <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ entry.text|linebreaks }}</p>
    </li>

    <p><a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a></p>


{% empty %}

<li>There is no entry for this topic yet.</li>
{% endfor %}
</ul>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p>Topics</p>

    <ul>

        {% for topic in Topics %}
        <!-- Display each topic as a clickable link -->
        <li><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic.text }}</a></li> 
        
        {% empty %}
        <li>No topics have been added yet.</li>
        {% endfor %}

    </ul>

    <a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}